name: Explore github workflow
run-name: List git main branch content
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: list repo content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: list repo content
        run: |
          git ls-tree -r main --name-only
          echo "Successful"